<?php

namespace Container7y2r6xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Usc9m3jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.usc9m3j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.usc9m3j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'readability' => ['privates', 'App\\Service\\ReadabilityService', 'getReadabilityServiceService', true],
            'repo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'readability' => 'App\\Service\\ReadabilityService',
            'repo' => 'App\\Repository\\ArticleRepository',
        ]);
    }
}
