<?php

namespace Container7y2r6xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1_UI1k5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1.UI1k5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'inscriptionRepo' => ['privates', 'App\\Repository\\InscriptionEvenementRepository', 'getInscriptionEvenementRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'waitlist' => ['privates', 'App\\Service\\WaitlistService', 'getWaitlistServiceService', true],
        ], [
            'inscriptionRepo' => 'App\\Repository\\InscriptionEvenementRepository',
            'repo' => 'App\\Repository\\EvenementRepository',
            'waitlist' => 'App\\Service\\WaitlistService',
        ]);

        if (isset($container->privates['.service_locator.1.UI1k5'])) {
            return $container->privates['.service_locator.1.UI1k5'];
        }

        return $container->privates['.service_locator.1.UI1k5'] = $instance;
    }
}
