<?php

namespace Container7y2r6xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZbxsEIcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZbxsEIc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZbxsEIc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'repo' => ['privates', 'App\\Repository\\SignalementArticleRepository', 'getSignalementArticleRepositoryService', true],
        ], [
            'articleRepo' => 'App\\Repository\\ArticleRepository',
            'em' => '?',
            'repo' => 'App\\Repository\\SignalementArticleRepository',
        ]);
    }
}
