<?php

namespace Container7y2r6xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RPn9qhZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rPn9qhZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rPn9qhZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailerService' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
            'qrCodeService' => ['privates', 'App\\Service\\QrCodeService', 'getQrCodeServiceService', true],
        ], [
            'mailerService' => 'App\\Service\\MailerService',
            'qrCodeService' => 'App\\Service\\QrCodeService',
        ]);
    }
}
