<?php

namespace Container7y2r6xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IevKdaGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IevKdaG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IevKdaG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'domaine' => ['privates', '.errored..service_locator.IevKdaG.App\\Entity\\DomaineCoaching', NULL, 'Cannot autowire service ".service_locator.IevKdaG": it needs an instance of "App\\Entity\\DomaineCoaching" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'domaine' => 'App\\Entity\\DomaineCoaching',
            'em' => '?',
        ]);
    }
}
