<?php

namespace Container7y2r6xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OEGgv3JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oEGgv3J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'inscriptionRepo' => ['privates', 'App\\Repository\\InscriptionEvenementRepository', 'getInscriptionEvenementRepositoryService', true],
            'waitlist' => ['privates', 'App\\Service\\WaitlistService', 'getWaitlistServiceService', true],
        ], [
            'em' => '?',
            'inscriptionRepo' => 'App\\Repository\\InscriptionEvenementRepository',
            'waitlist' => 'App\\Service\\WaitlistService',
        ]);

        if (isset($container->privates['.service_locator.oEGgv3J'])) {
            return $container->privates['.service_locator.oEGgv3J'];
        }

        return $container->privates['.service_locator.oEGgv3J'] = $instance;
    }
}
