<?php

namespace Container7y2r6xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BuQvOyBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BuQvOyB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BuQvOyB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reactionRepository' => ['privates', 'App\\Repository\\ArticleReactionRepository', 'getArticleReactionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'reactionRepository' => 'App\\Repository\\ArticleReactionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
