<?php

namespace Container7y2r6xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BTDSyFEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BTDSyFE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BTDSyFE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coach' => ['privates', '.errored..service_locator.BTDSyFE.App\\Entity\\Coach', NULL, 'Cannot autowire service ".service_locator.BTDSyFE": it needs an instance of "App\\Entity\\Coach" but this type has been excluded in "config/services.yaml".'],
        ], [
            'coach' => 'App\\Entity\\Coach',
        ]);
    }
}
