<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Coach__CLASSMETADATA__' => 0,
'App__Entity__DomaineCoaching__CLASSMETADATA__' => 1,
'App__Entity__Evenement__CLASSMETADATA__' => 2,
'App__Entity__Reservation__CLASSMETADATA__' => 3,
'App__Entity__InscriptionEvenement__CLASSMETADATA__' => 4,
'App__Entity__Article__CLASSMETADATA__' => 5,
'App__Entity__ArticleReaction__CLASSMETADATA__' => 6,
'App__Entity__Commande__CLASSMETADATA__' => 7,
'App__Entity__CommentaireEvenement__CLASSMETADATA__' => 8,
'App__Entity__Disponibilite__CLASSMETADATA__' => 9,
'App__Entity__Product__CLASSMETADATA__' => 10,
'App__Entity__Rating__CLASSMETADATA__' => 11,
'App__Entity__ReviewCache__CLASSMETADATA__' => 12,
'App__Entity__Role__CLASSMETADATA__' => 13,
'App__Entity__SignalementArticle__CLASSMETADATA__' => 14,
'App__Entity__User__CLASSMETADATA__' => 15,
'App__Entity__Vendor__CLASSMETADATA__' => 16,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Coach',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CoachRepository',
            ],
            'identifier' => [
                [
                    'idCoach',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'idCoach' => $o[1],
                    'nom' => $o[2],
                    'prenom' => $o[3],
                    'biographie' => $o[4],
                    'experienceAnnees' => $o[5],
                    'tarifHoraire' => $o[6],
                    'disponibilite' => $o[7],
                    'domaine' => $o[8],
                    'numTel' => $o[9],
                    'noteMoyenne' => $o[10],
                ],
            ],
            'fieldNames' => [
                [
                    'id_coach' => 'idCoach',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'biographie' => 'biographie',
                    'experience_annees' => 'experienceAnnees',
                    'tarif_horaire' => 'tarifHoraire',
                    'disponibilite' => 'disponibilite',
                    'domaine' => 'domaine',
                    'num_tel' => 'numTel',
                    'note_moyenne' => 'noteMoyenne',
                ],
            ],
            'columnNames' => [
                [
                    'idCoach' => 'id_coach',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'biographie' => 'biographie',
                    'experienceAnnees' => 'experience_annees',
                    'tarifHoraire' => 'tarif_horaire',
                    'disponibilite' => 'disponibilite',
                    'domaine' => 'domaine',
                    'numTel' => 'num_tel',
                    'noteMoyenne' => 'note_moyenne',
                ],
            ],
            'table' => [
                [
                    'name' => 'coach',
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[11],
                    'domaineCoaching' => $o[13],
                ],
            ],
            'idGenerator' => [
                $o[15],
            ],
            'name' => [
                'App\\Entity\\Coach',
                12 => 'id_user',
                14 => 'id_domaine',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'text',
                'integer',
                'decimal',
                'string',
                'string',
                'string',
                'decimal',
            ],
            'fieldName' => [
                1 => 'idCoach',
                'nom',
                'prenom',
                'biographie',
                'experienceAnnees',
                'tarifHoraire',
                'disponibilite',
                'domaine',
                'numTel',
                'noteMoyenne',
            ],
            'columnName' => [
                1 => 'id_coach',
                'nom',
                'prenom',
                'biographie',
                'experience_annees',
                'tarif_horaire',
                'disponibilite',
                'domaine',
                'num_tel',
                'note_moyenne',
            ],
            'length' => [
                2 => 20,
                20,
                7 => 20,
                50,
                20,
            ],
            'nullable' => [
                4 => true,
                true,
                true,
                true,
                true,
                true,
                true,
                12 => true,
                14 => true,
            ],
            'columnDefinition' => [
                4 => 'TEXT DEFAULT NULL',
            ],
            'precision' => [
                6 => 10,
                10 => 3,
            ],
            'scale' => [
                6 => 2,
                10 => 2,
            ],
            'fetch' => [
                11 => 2,
                13 => 2,
            ],
            'sourceEntity' => [
                11 => 'App\\Entity\\Coach',
                13 => 'App\\Entity\\Coach',
            ],
            'sourceToTargetKeyColumns' => [
                11 => [
                    'id_user' => 'id_user',
                ],
                13 => [
                    'id_domaine' => 'id_domaine',
                ],
            ],
            'targetToSourceKeyColumns' => [
                11 => [
                    'id_user' => 'id_user',
                ],
                13 => [
                    'id_domaine' => 'id_domaine',
                ],
            ],
            'joinColumns' => [
                11 => [
                    $o[12],
                ],
                13 => [
                    $o[14],
                ],
            ],
            'joinColumnFieldNames' => [
                11 => [
                    'id_user' => 'id_user',
                ],
                13 => [
                    'id_domaine' => 'id_domaine',
                ],
            ],
            'deferrable' => [
                12 => false,
                14 => false,
            ],
            'unique' => [
                12 => false,
                14 => false,
            ],
            'onDelete' => [
                12 => 'SET NULL',
                14 => 'CASCADE',
            ],
            'referencedColumnName' => [
                12 => 'id_user',
                14 => 'id_domaine',
            ],
            'inversedBy' => [
                13 => 'coaches',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                11 => 'user',
                13 => 'domaineCoaching',
            ],
            'targetEntity' => [
                11 => 'App\\Entity\\User',
                13 => 'App\\Entity\\DomaineCoaching',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\DomaineCoaching',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DomaineCoachingRepository',
            ],
            'identifier' => [
                [
                    'idDomaine',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'idDomaine' => $o[1],
                    'nomDomaine' => $o[2],
                    'description' => $o[3],
                    'niveauDifficulte' => $o[4],
                    'dureeFormationHeures' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id_domaine' => 'idDomaine',
                    'nom_domaine' => 'nomDomaine',
                    'description' => 'description',
                    'niveau_difficulte' => 'niveauDifficulte',
                    'duree_formation_heures' => 'dureeFormationHeures',
                ],
            ],
            'columnNames' => [
                [
                    'idDomaine' => 'id_domaine',
                    'nomDomaine' => 'nom_domaine',
                    'description' => 'description',
                    'niveauDifficulte' => 'niveau_difficulte',
                    'dureeFormationHeures' => 'duree_formation_heures',
                ],
            ],
            'table' => [
                [
                    'name' => 'domaine_coaching',
                ],
            ],
            'associationMappings' => [
                [
                    'coaches' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\DomaineCoaching',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'string',
                'integer',
            ],
            'fieldName' => [
                1 => 'idDomaine',
                'nomDomaine',
                'description',
                'niveauDifficulte',
                'dureeFormationHeures',
            ],
            'columnName' => [
                1 => 'id_domaine',
                'nom_domaine',
                'description',
                'niveau_difficulte',
                'duree_formation_heures',
            ],
            'length' => [
                2 => 100,
                4 => 20,
            ],
            'unique' => [
                2 => true,
            ],
            'nullable' => [
                3 => true,
                5 => true,
            ],
            'options' => [
                4 => [
                    'default' => 'Débutant',
                ],
            ],
            'fetch' => [
                6 => 2,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\DomaineCoaching',
            ],
            'mappedBy' => [
                6 => 'domaineCoaching',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'coaches',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\Coach',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Evenement',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\EvenementRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'description' => $o[3],
                    'price' => $o[4],
                    'date' => $o[5],
                    'capacity' => $o[6],
                    'image' => $o[7],
                    'lieu' => $o[8],
                    'aiRating' => $o[9],
                    'aiPositive' => $o[10],
                    'aiNeutral' => $o[11],
                    'aiNegative' => $o[12],
                    'aiSummary' => $o[13],
                ],
            ],
            'fieldNames' => [
                [
                    'id_evenement' => 'id',
                    'titre' => 'title',
                    'description' => 'description',
                    'prix' => 'price',
                    'date_debut' => 'date',
                    'capacite_max' => 'capacity',
                    'image_url' => 'image',
                    'lieu' => 'lieu',
                    'ai_rating' => 'aiRating',
                    'ai_positive' => 'aiPositive',
                    'ai_neutral' => 'aiNeutral',
                    'ai_negative' => 'aiNegative',
                    'ai_summary' => 'aiSummary',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_evenement',
                    'title' => 'titre',
                    'description' => 'description',
                    'price' => 'prix',
                    'date' => 'date_debut',
                    'capacity' => 'capacite_max',
                    'image' => 'image_url',
                    'lieu' => 'lieu',
                    'aiRating' => 'ai_rating',
                    'aiPositive' => 'ai_positive',
                    'aiNeutral' => 'ai_neutral',
                    'aiNegative' => 'ai_negative',
                    'aiSummary' => 'ai_summary',
                ],
            ],
            'table' => [
                [
                    'name' => 'evenement',
                ],
            ],
            'associationMappings' => [
                [
                    'commentaires' => $o[14],
                ],
            ],
            'idGenerator' => [
                $o[15],
            ],
            'name' => [
                'App\\Entity\\Evenement',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'decimal',
                'datetime',
                'integer',
                'string',
                'string',
                'float',
                'float',
                'float',
                'float',
                'text',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'description',
                'price',
                'date',
                'capacity',
                'image',
                'lieu',
                'aiRating',
                'aiPositive',
                'aiNeutral',
                'aiNegative',
                'aiSummary',
            ],
            'columnName' => [
                1 => 'id_evenement',
                'titre',
                'description',
                'prix',
                'date_debut',
                'capacite_max',
                'image_url',
                'lieu',
                'ai_rating',
                'ai_positive',
                'ai_neutral',
                'ai_negative',
                'ai_summary',
            ],
            'length' => [
                2 => 200,
                7 => 500,
                255,
            ],
            'nullable' => [
                3 => true,
                true,
                6 => true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
            ],
            'precision' => [
                4 => 10,
            ],
            'scale' => [
                4 => 2,
            ],
            'cascade' => [
                14 => [
                    'persist',
                    'remove',
                ],
            ],
            'fetch' => [
                14 => 2,
            ],
            'orphanRemoval' => [
                14 => true,
            ],
            'sourceEntity' => [
                14 => 'App\\Entity\\Evenement',
            ],
            'mappedBy' => [
                14 => 'evenement',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                14 => 'commentaires',
            ],
            'targetEntity' => [
                14 => 'App\\Entity\\CommentaireEvenement',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Reservation',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ReservationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'dateReservation' => $o[2],
                    'dateSeance' => $o[3],
                    'statut' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id_reservation' => 'id',
                    'date_reservation' => 'dateReservation',
                    'date_seance' => 'dateSeance',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_reservation',
                    'dateReservation' => 'date_reservation',
                    'dateSeance' => 'date_seance',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'reservation',
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[5],
                    'coach' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[9],
            ],
            'name' => [
                'App\\Entity\\Reservation',
                6 => 'id_user',
                8 => 'id_coach',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime',
                'date',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'dateReservation',
                'dateSeance',
                'statut',
            ],
            'columnName' => [
                1 => 'id_reservation',
                'date_reservation',
                'date_seance',
                'statut',
            ],
            'nullable' => [
                3 => true,
                6 => false,
                8 => false,
            ],
            'length' => [
                4 => 20,
            ],
            'fetch' => [
                5 => 2,
                7 => 2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\Reservation',
                7 => 'App\\Entity\\Reservation',
            ],
            'sourceToTargetKeyColumns' => [
                5 => [
                    'id_user' => 'id_user',
                ],
                7 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'targetToSourceKeyColumns' => [
                5 => [
                    'id_user' => 'id_user',
                ],
                7 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'joinColumns' => [
                5 => [
                    $o[6],
                ],
                7 => [
                    $o[8],
                ],
            ],
            'joinColumnFieldNames' => [
                5 => [
                    'id_user' => 'id_user',
                ],
                7 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'deferrable' => [
                6 => false,
                8 => false,
            ],
            'unique' => [
                6 => false,
                8 => false,
            ],
            'onDelete' => [
                6 => 'CASCADE',
                8 => 'CASCADE',
            ],
            'referencedColumnName' => [
                6 => 'id_user',
                8 => 'id_coach',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'user',
                7 => 'coach',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\User',
                7 => 'App\\Entity\\Coach',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\InscriptionEvenement',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\InscriptionEvenementRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'dateReservation' => $o[2],
                    'statut' => $o[3],
                    'nom' => $o[4],
                    'email' => $o[5],
                    'telephone' => $o[6],
                    'nombrePlaces' => $o[7],
                    'paymentStatus' => $o[8],
                    'stripeSessionId' => $o[9],
                    'montantTotal' => $o[10],
                    'devise' => $o[11],
                    'paidAt' => $o[12],
                ],
            ],
            'fieldNames' => [
                [
                    'id_inscription' => 'id',
                    'date_inscription' => 'dateReservation',
                    'statut' => 'statut',
                    'nom' => 'nom',
                    'email' => 'email',
                    'telephone' => 'telephone',
                    'nombre_places' => 'nombrePlaces',
                    'payment_status' => 'paymentStatus',
                    'stripe_session_id' => 'stripeSessionId',
                    'montant_total' => 'montantTotal',
                    'devise' => 'devise',
                    'paid_at' => 'paidAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_inscription',
                    'dateReservation' => 'date_inscription',
                    'statut' => 'statut',
                    'nom' => 'nom',
                    'email' => 'email',
                    'telephone' => 'telephone',
                    'nombrePlaces' => 'nombre_places',
                    'paymentStatus' => 'payment_status',
                    'stripeSessionId' => 'stripe_session_id',
                    'montantTotal' => 'montant_total',
                    'devise' => 'devise',
                    'paidAt' => 'paid_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'inscription_evenement',
                ],
            ],
            'associationMappings' => [
                [
                    'evenement' => $o[13],
                    'user' => $o[15],
                ],
            ],
            'idGenerator' => [
                $o[17],
            ],
            'name' => [
                'App\\Entity\\InscriptionEvenement',
                14 => 'id_evenement',
                16 => 'id_user',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime',
                'string',
                'string',
                'string',
                'string',
                'integer',
                'string',
                'string',
                'decimal',
                'string',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'dateReservation',
                'statut',
                'nom',
                'email',
                'telephone',
                'nombrePlaces',
                'paymentStatus',
                'stripeSessionId',
                'montantTotal',
                'devise',
                'paidAt',
            ],
            'columnName' => [
                1 => 'id_inscription',
                'date_inscription',
                'statut',
                'nom',
                'email',
                'telephone',
                'nombre_places',
                'payment_status',
                'stripe_session_id',
                'montant_total',
                'devise',
                'paid_at',
            ],
            'nullable' => [
                2 => true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                14 => true,
                16 => true,
            ],
            'length' => [
                3 => 20,
                100,
                150,
                20,
                8 => 30,
                255,
                11 => 10,
            ],
            'options' => [
                8 => [
                    'default' => 'pending',
                ],
                11 => [
                    'default' => 'tnd',
                ],
            ],
            'precision' => [
                10 => 10,
            ],
            'scale' => [
                10 => 2,
            ],
            'fetch' => [
                13 => 2,
                15 => 2,
            ],
            'sourceEntity' => [
                13 => 'App\\Entity\\InscriptionEvenement',
                15 => 'App\\Entity\\InscriptionEvenement',
            ],
            'sourceToTargetKeyColumns' => [
                13 => [
                    'id_evenement' => 'id_evenement',
                ],
                15 => [
                    'id_user' => 'id_user',
                ],
            ],
            'targetToSourceKeyColumns' => [
                13 => [
                    'id_evenement' => 'id_evenement',
                ],
                15 => [
                    'id_user' => 'id_user',
                ],
            ],
            'joinColumns' => [
                13 => [
                    $o[14],
                ],
                15 => [
                    $o[16],
                ],
            ],
            'joinColumnFieldNames' => [
                13 => [
                    'id_evenement' => 'id_evenement',
                ],
                15 => [
                    'id_user' => 'id_user',
                ],
            ],
            'deferrable' => [
                14 => false,
                16 => false,
            ],
            'unique' => [
                14 => false,
                16 => false,
            ],
            'referencedColumnName' => [
                14 => 'id_evenement',
                16 => 'id_user',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                13 => 'evenement',
                15 => 'user',
            ],
            'targetEntity' => [
                13 => 'App\\Entity\\Evenement',
                15 => 'App\\Entity\\User',
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Article',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ArticleRepository',
            ],
            'identifier' => [
                [
                    'id_article',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id_article' => $o[1],
                    'titre' => $o[2],
                    'contenu' => $o[3],
                    'image_principale' => $o[4],
                    'categorie' => $o[5],
                    'statut' => $o[6],
                    'nombre_vues' => $o[7],
                    'mots_cles' => $o[8],
                    'resume_ia' => $o[9],
                    'ton_ia' => $o[10],
                    'categorie_ia' => $o[11],
                    'trending_score' => $o[12],
                    'trending_updated_at' => $o[13],
                ],
            ],
            'fieldNames' => [
                [
                    'id_article' => 'id_article',
                    'titre' => 'titre',
                    'contenu' => 'contenu',
                    'image_principale' => 'image_principale',
                    'categorie' => 'categorie',
                    'statut' => 'statut',
                    'nombre_vues' => 'nombre_vues',
                    'mots_cles' => 'mots_cles',
                    'resume_ia' => 'resume_ia',
                    'ton_ia' => 'ton_ia',
                    'categorie_ia' => 'categorie_ia',
                    'trending_score' => 'trending_score',
                    'trending_updated_at' => 'trending_updated_at',
                ],
            ],
            'columnNames' => [
                [
                    'id_article' => 'id_article',
                    'titre' => 'titre',
                    'contenu' => 'contenu',
                    'image_principale' => 'image_principale',
                    'categorie' => 'categorie',
                    'statut' => 'statut',
                    'nombre_vues' => 'nombre_vues',
                    'mots_cles' => 'mots_cles',
                    'resume_ia' => 'resume_ia',
                    'ton_ia' => 'ton_ia',
                    'categorie_ia' => 'categorie_ia',
                    'trending_score' => 'trending_score',
                    'trending_updated_at' => 'trending_updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'article',
                ],
            ],
            'idGenerator' => [
                $o[14],
            ],
            'name' => [
                'App\\Entity\\Article',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'string',
                'string',
                'string',
                'integer',
                'string',
                'text',
                'string',
                'string',
                'float',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id_article',
                'titre',
                'contenu',
                'image_principale',
                'categorie',
                'statut',
                'nombre_vues',
                'mots_cles',
                'resume_ia',
                'ton_ia',
                'categorie_ia',
                'trending_score',
                'trending_updated_at',
            ],
            'columnName' => [
                1 => 'id_article',
                'titre',
                'contenu',
                'image_principale',
                'categorie',
                'statut',
                'nombre_vues',
                'mots_cles',
                'resume_ia',
                'ton_ia',
                'categorie_ia',
                'trending_score',
                'trending_updated_at',
            ],
            'length' => [
                2 => 255,
                4 => 255,
                100,
                20,
                8 => 500,
                10 => 30,
                100,
            ],
            'nullable' => [
                4 => true,
                true,
                true,
                8 => true,
                true,
                true,
                true,
                true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\ArticleReaction',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ArticleReactionRepository',
            ],
            'identifier' => [
                [
                    'id_reaction',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id_reaction' => $o[1],
                    'id_article' => $o[2],
                    'id_user' => $o[3],
                    'type_reaction' => $o[4],
                    'note' => $o[5],
                    'avis' => $o[6],
                    'date_reaction' => $o[7],
                    'is_anonymous' => $o[8],
                ],
            ],
            'fieldNames' => [
                [
                    'id_reaction' => 'id_reaction',
                    'id_article' => 'id_article',
                    'id_user' => 'id_user',
                    'type_reaction' => 'type_reaction',
                    'note' => 'note',
                    'avis' => 'avis',
                    'date_reaction' => 'date_reaction',
                    'is_anonymous' => 'is_anonymous',
                ],
            ],
            'columnNames' => [
                [
                    'id_reaction' => 'id_reaction',
                    'id_article' => 'id_article',
                    'id_user' => 'id_user',
                    'type_reaction' => 'type_reaction',
                    'note' => 'note',
                    'avis' => 'avis',
                    'date_reaction' => 'date_reaction',
                    'is_anonymous' => 'is_anonymous',
                ],
            ],
            'table' => [
                [
                    'name' => 'article_reaction',
                    'uniqueConstraints' => [
                        'uq_user_article_type' => [
                            'columns' => [
                                'id_user',
                                'id_article',
                                'type_reaction',
                            ],
                        ],
                    ],
                ],
            ],
            'idGenerator' => [
                $o[9],
            ],
            'name' => [
                'App\\Entity\\ArticleReaction',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'integer',
                'integer',
                'string',
                'smallint',
                'string',
                'datetime_immutable',
                'boolean',
            ],
            'fieldName' => [
                1 => 'id_reaction',
                'id_article',
                'id_user',
                'type_reaction',
                'note',
                'avis',
                'date_reaction',
                'is_anonymous',
            ],
            'columnName' => [
                1 => 'id_reaction',
                'id_article',
                'id_user',
                'type_reaction',
                'note',
                'avis',
                'date_reaction',
                'is_anonymous',
            ],
            'length' => [
                4 => 20,
                6 => 500,
            ],
            'nullable' => [
                5 => true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },
7 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Commande',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CommandeRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'dateCommande' => $o[2],
                    'montantTotal' => $o[3],
                    'statut' => $o[4],
                    'modePaiement' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id_commande' => 'id',
                    'date_commande' => 'dateCommande',
                    'montant_total' => 'montantTotal',
                    'statut' => 'statut',
                    'mode_paiement' => 'modePaiement',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_commande',
                    'dateCommande' => 'date_commande',
                    'montantTotal' => 'montant_total',
                    'statut' => 'statut',
                    'modePaiement' => 'mode_paiement',
                ],
            ],
            'table' => [
                [
                    'name' => 'commande',
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\Commande',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'date',
                'decimal',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'dateCommande',
                'montantTotal',
                'statut',
                'modePaiement',
            ],
            'columnName' => [
                1 => 'id_commande',
                'date_commande',
                'montant_total',
                'statut',
                'mode_paiement',
            ],
            'precision' => [
                3 => 10,
            ],
            'scale' => [
                3 => 2,
            ],
            'length' => [
                4 => 20,
                50,
            ],
            'nullable' => [
                4 => true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },
8 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\CommentaireEvenement',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CommentaireEvenementRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'contenu' => $o[2],
                    'note' => $o[3],
                    'dateCreation' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id_commentaire' => 'id',
                    'contenu' => 'contenu',
                    'note' => 'note',
                    'date_creation' => 'dateCreation',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_commentaire',
                    'contenu' => 'contenu',
                    'note' => 'note',
                    'dateCreation' => 'date_creation',
                ],
            ],
            'table' => [
                [
                    'name' => 'commentaire_evenement',
                ],
            ],
            'associationMappings' => [
                [
                    'evenement' => $o[5],
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\CommentaireEvenement',
                6 => 'evenement_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'text',
                'integer',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'contenu',
                'note',
                'dateCreation',
            ],
            'columnName' => [
                1 => 'id_commentaire',
                'contenu',
                'note',
                'date_creation',
            ],
            'nullable' => [
                3 => true,
                6 => false,
            ],
            'fetch' => [
                5 => 2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\CommentaireEvenement',
            ],
            'inversedBy' => [
                5 => 'commentaires',
            ],
            'sourceToTargetKeyColumns' => [
                5 => [
                    'evenement_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                5 => [
                    'id' => 'evenement_id',
                ],
            ],
            'joinColumns' => [
                5 => [
                    $o[6],
                ],
            ],
            'joinColumnFieldNames' => [
                5 => [
                    'evenement_id' => 'evenement_id',
                ],
            ],
            'deferrable' => [
                6 => false,
            ],
            'unique' => [
                6 => false,
            ],
            'referencedColumnName' => [
                6 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'evenement',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\Evenement',
            ],
        ],
    ],
    $o[0],
    []
); } },
9 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Disponibilite',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DisponibiliteRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'jour' => $o[2],
                    'statut' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'id_dispo' => 'id',
                    'jour' => 'jour',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_dispo',
                    'jour' => 'jour',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'disponibilite',
                ],
            ],
            'associationMappings' => [
                [
                    'coach' => $o[4],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\Disponibilite',
                5 => 'id_coach',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'date',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'jour',
                'statut',
            ],
            'columnName' => [
                1 => 'id_dispo',
                'jour',
                'statut',
            ],
            'length' => [
                3 => 20,
            ],
            'fetch' => [
                4 => 2,
            ],
            'sourceEntity' => [
                4 => 'App\\Entity\\Disponibilite',
            ],
            'sourceToTargetKeyColumns' => [
                4 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'targetToSourceKeyColumns' => [
                4 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'joinColumns' => [
                4 => [
                    $o[5],
                ],
            ],
            'joinColumnFieldNames' => [
                4 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'deferrable' => [
                5 => false,
            ],
            'unique' => [
                5 => false,
            ],
            'onDelete' => [
                5 => 'CASCADE',
            ],
            'nullable' => [
                5 => false,
            ],
            'referencedColumnName' => [
                5 => 'id_coach',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                4 => 'coach',
            ],
            'targetEntity' => [
                4 => 'App\\Entity\\Coach',
            ],
        ],
    ],
    $o[0],
    []
); } },
10 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Product',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ProductRepository',
            ],
            'identifier' => [
                [
                    'idProduit',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'idProduit' => $o[1],
                    'nomProduit' => $o[2],
                    'description' => $o[3],
                    'prix' => $o[4],
                    'stockDisponible' => $o[5],
                    'categorie' => $o[6],
                    'imageUrl' => $o[7],
                    'statut' => $o[8],
                    'rating' => $o[9],
                    'ratingCount' => $o[10],
                ],
            ],
            'fieldNames' => [
                [
                    'id_produit' => 'idProduit',
                    'nom_produit' => 'nomProduit',
                    'description' => 'description',
                    'prix' => 'prix',
                    'stock_disponible' => 'stockDisponible',
                    'categorie' => 'categorie',
                    'image_url' => 'imageUrl',
                    'statut' => 'statut',
                    'rating' => 'rating',
                    'rating_count' => 'ratingCount',
                ],
            ],
            'columnNames' => [
                [
                    'idProduit' => 'id_produit',
                    'nomProduit' => 'nom_produit',
                    'description' => 'description',
                    'prix' => 'prix',
                    'stockDisponible' => 'stock_disponible',
                    'categorie' => 'categorie',
                    'imageUrl' => 'image_url',
                    'statut' => 'statut',
                    'rating' => 'rating',
                    'ratingCount' => 'rating_count',
                ],
            ],
            'table' => [
                [
                    'name' => 'produit',
                ],
            ],
            'associationMappings' => [
                [
                    'vendeur' => $o[11],
                ],
            ],
            'idGenerator' => [
                $o[13],
            ],
            'name' => [
                'App\\Entity\\Product',
                12 => 'vendor_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'decimal',
                'integer',
                'string',
                'string',
                'string',
                'float',
                'integer',
            ],
            'fieldName' => [
                1 => 'idProduit',
                'nomProduit',
                'description',
                'prix',
                'stockDisponible',
                'categorie',
                'imageUrl',
                'statut',
                'rating',
                'ratingCount',
            ],
            'columnName' => [
                1 => 'id_produit',
                'nom_produit',
                'description',
                'prix',
                'stock_disponible',
                'categorie',
                'image_url',
                'statut',
                'rating',
                'rating_count',
            ],
            'length' => [
                2 => 200,
                6 => 100,
                500,
                20,
            ],
            'nullable' => [
                3 => true,
                5 => true,
                true,
                true,
                true,
                true,
                true,
                12 => true,
            ],
            'precision' => [
                4 => 10,
            ],
            'scale' => [
                4 => 2,
            ],
            'fetch' => [
                11 => 2,
            ],
            'sourceEntity' => [
                11 => 'App\\Entity\\Product',
            ],
            'inversedBy' => [
                11 => 'products',
            ],
            'sourceToTargetKeyColumns' => [
                11 => [
                    'vendor_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                11 => [
                    'id' => 'vendor_id',
                ],
            ],
            'joinColumns' => [
                11 => [
                    $o[12],
                ],
            ],
            'joinColumnFieldNames' => [
                11 => [
                    'vendor_id' => 'vendor_id',
                ],
            ],
            'deferrable' => [
                12 => false,
            ],
            'unique' => [
                12 => false,
            ],
            'onDelete' => [
                12 => 'SET NULL',
            ],
            'referencedColumnName' => [
                12 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                11 => 'vendeur',
            ],
            'targetEntity' => [
                11 => 'App\\Entity\\Vendor',
            ],
        ],
    ],
    $o[0],
    []
); } },
11 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Rating',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\RatingRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'note' => $o[2],
                    'commentaire' => $o[3],
                    'dateCreation' => $o[4],
                    'dateModification' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id_rating' => 'id',
                    'note' => 'note',
                    'commentaire' => 'commentaire',
                    'date_creation' => 'dateCreation',
                    'date_modification' => 'dateModification',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_rating',
                    'note' => 'note',
                    'commentaire' => 'commentaire',
                    'dateCreation' => 'date_creation',
                    'dateModification' => 'date_modification',
                ],
            ],
            'table' => [
                [
                    'name' => 'rating',
                    'uniqueConstraints' => [
                        'UNIQ_RATING_USER_COACH' => [
                            'columns' => [
                                'id_user',
                                'id_coach',
                            ],
                        ],
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[6],
                    'coach' => $o[8],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Rating',
                7 => 'id_user',
                9 => 'id_coach',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'integer',
                'text',
                'datetime',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'note',
                'commentaire',
                'dateCreation',
                'dateModification',
            ],
            'columnName' => [
                1 => 'id_rating',
                'note',
                'commentaire',
                'date_creation',
                'date_modification',
            ],
            'nullable' => [
                3 => true,
                7 => false,
                9 => false,
            ],
            'fetch' => [
                6 => 2,
                8 => 2,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\Rating',
                8 => 'App\\Entity\\Rating',
            ],
            'sourceToTargetKeyColumns' => [
                6 => [
                    'id_user' => 'id_user',
                ],
                8 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'targetToSourceKeyColumns' => [
                6 => [
                    'id_user' => 'id_user',
                ],
                8 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'joinColumns' => [
                6 => [
                    $o[7],
                ],
                8 => [
                    $o[9],
                ],
            ],
            'joinColumnFieldNames' => [
                6 => [
                    'id_user' => 'id_user',
                ],
                8 => [
                    'id_coach' => 'id_coach',
                ],
            ],
            'deferrable' => [
                7 => false,
                9 => false,
            ],
            'unique' => [
                7 => false,
                9 => false,
            ],
            'onDelete' => [
                7 => 'CASCADE',
                9 => 'CASCADE',
            ],
            'referencedColumnName' => [
                7 => 'id_user',
                9 => 'id_coach',
            ],
            'cascade' => [
                8 => [
                    'persist',
                ],
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'user',
                8 => 'coach',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\User',
                8 => 'App\\Entity\\Coach',
            ],
        ],
    ],
    $o[0],
    []
); } },
12 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\ReviewCache',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ReviewCacheRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'productId' => $o[2],
                    'data' => $o[3],
                    'updatedAt' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'product_id' => 'productId',
                    'data' => 'data',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'productId' => 'product_id',
                    'data' => 'data',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'review_cache',
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'name' => [
                'App\\Entity\\ReviewCache',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'json',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'productId',
                'data',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'product_id',
                'data',
                'updated_at',
            ],
            'length' => [
                2 => 255,
            ],
        ],
    ],
    $o[0],
    []
); } },
13 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Role',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\RoleRepository',
            ],
            'identifier' => [
                [
                    'idRole',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'idRole' => $o[1],
                    'nomRole' => $o[2],
                ],
            ],
            'fieldNames' => [
                [
                    'id_role' => 'idRole',
                    'nom_role' => 'nomRole',
                ],
            ],
            'columnNames' => [
                [
                    'idRole' => 'id_role',
                    'nomRole' => 'nom_role',
                ],
            ],
            'table' => [
                [
                    'name' => 'role',
                ],
            ],
            'idGenerator' => [
                $o[3],
            ],
            'name' => [
                'App\\Entity\\Role',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
            ],
            'fieldName' => [
                1 => 'idRole',
                'nomRole',
            ],
            'columnName' => [
                1 => 'id_role',
                'nom_role',
            ],
            'length' => [
                2 => 50,
            ],
        ],
    ],
    $o[0],
    []
); } },
14 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\SignalementArticle',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\SignalementArticleRepository',
            ],
            'identifier' => [
                [
                    'id_signalement',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id_signalement' => $o[1],
                    'id_article' => $o[2],
                    'id_user' => $o[3],
                    'motif' => $o[4],
                    'description' => $o[5],
                    'statut' => $o[6],
                    'date_signalement' => $o[7],
                    'date_traitement' => $o[8],
                    'remarque_admin' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id_signalement' => 'id_signalement',
                    'id_article' => 'id_article',
                    'id_user' => 'id_user',
                    'motif' => 'motif',
                    'description' => 'description',
                    'statut' => 'statut',
                    'date_signalement' => 'date_signalement',
                    'date_traitement' => 'date_traitement',
                    'remarque_admin' => 'remarque_admin',
                ],
            ],
            'columnNames' => [
                [
                    'id_signalement' => 'id_signalement',
                    'id_article' => 'id_article',
                    'id_user' => 'id_user',
                    'motif' => 'motif',
                    'description' => 'description',
                    'statut' => 'statut',
                    'date_signalement' => 'date_signalement',
                    'date_traitement' => 'date_traitement',
                    'remarque_admin' => 'remarque_admin',
                ],
            ],
            'table' => [
                [
                    'name' => 'article_signalement',
                    'uniqueConstraints' => [
                        'uq_user_article_signalement' => [
                            'columns' => [
                                'id_user',
                                'id_article',
                            ],
                        ],
                    ],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\SignalementArticle',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'integer',
                'integer',
                'string',
                'text',
                'string',
                'datetime_immutable',
                'datetime_immutable',
                'text',
            ],
            'fieldName' => [
                1 => 'id_signalement',
                'id_article',
                'id_user',
                'motif',
                'description',
                'statut',
                'date_signalement',
                'date_traitement',
                'remarque_admin',
            ],
            'columnName' => [
                1 => 'id_signalement',
                'id_article',
                'id_user',
                'motif',
                'description',
                'statut',
                'date_signalement',
                'date_traitement',
                'remarque_admin',
            ],
            'length' => [
                4 => 50,
                6 => 20,
            ],
            'nullable' => [
                5 => true,
                8 => true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },
15 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'prenom' => $o[3],
                    'email' => $o[4],
                    'password' => $o[5],
                    'telephone' => $o[6],
                    'adresse' => $o[7],
                    'statut' => $o[8],
                    'dateInscription' => $o[9],
                    'derniereConnexion' => $o[10],
                ],
            ],
            'fieldNames' => [
                [
                    'id_user' => 'id',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'password' => 'password',
                    'telephone' => 'telephone',
                    'adresse' => 'adresse',
                    'statut' => 'statut',
                    'date_inscription' => 'dateInscription',
                    'derniere_connexion' => 'derniereConnexion',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_user',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'password' => 'password',
                    'telephone' => 'telephone',
                    'adresse' => 'adresse',
                    'statut' => 'statut',
                    'dateInscription' => 'date_inscription',
                    'derniereConnexion' => 'derniere_connexion',
                ],
            ],
            'table' => [
                [
                    'name' => 'users',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onCreate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'role' => $o[11],
                ],
            ],
            'idGenerator' => [
                $o[13],
            ],
            'name' => [
                'App\\Entity\\User',
                12 => 'id_role',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'prenom',
                'email',
                'password',
                'telephone',
                'adresse',
                'statut',
                'dateInscription',
                'derniereConnexion',
            ],
            'columnName' => [
                1 => 'id_user',
                'nom',
                'prenom',
                'email',
                'password',
                'telephone',
                'adresse',
                'statut',
                'date_inscription',
                'derniere_connexion',
            ],
            'length' => [
                2 => 100,
                100,
                100,
                255,
                20,
                255,
                20,
            ],
            'unique' => [
                4 => true,
                12 => false,
            ],
            'nullable' => [
                6 => true,
                true,
                true,
                true,
                true,
                12 => true,
            ],
            'fetch' => [
                11 => 2,
            ],
            'sourceEntity' => [
                11 => 'App\\Entity\\User',
            ],
            'sourceToTargetKeyColumns' => [
                11 => [
                    'id_role' => 'id_role',
                ],
            ],
            'targetToSourceKeyColumns' => [
                11 => [
                    'id_role' => 'id_role',
                ],
            ],
            'joinColumns' => [
                11 => [
                    $o[12],
                ],
            ],
            'joinColumnFieldNames' => [
                11 => [
                    'id_role' => 'id_role',
                ],
            ],
            'deferrable' => [
                12 => false,
            ],
            'referencedColumnName' => [
                12 => 'id_role',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                11 => 'role',
            ],
            'targetEntity' => [
                11 => 'App\\Entity\\Role',
            ],
        ],
    ],
    $o[0],
    []
); } },
16 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Vendor',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\VendorRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'email' => $o[3],
                    'telephone' => $o[4],
                    'statut' => $o[5],
                    'rating' => $o[6],
                    'ratingCount' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'email' => 'email',
                    'telephone' => 'telephone',
                    'statut' => 'statut',
                    'rating' => 'rating',
                    'rating_count' => 'ratingCount',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'email' => 'email',
                    'telephone' => 'telephone',
                    'statut' => 'statut',
                    'rating' => 'rating',
                    'ratingCount' => 'rating_count',
                ],
            ],
            'table' => [
                [
                    'name' => 'vendor',
                ],
            ],
            'associationMappings' => [
                [
                    'products' => $o[8],
                ],
            ],
            'idGenerator' => [
                $o[9],
            ],
            'name' => [
                'App\\Entity\\Vendor',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'float',
                'integer',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'email',
                'telephone',
                'statut',
                'rating',
                'ratingCount',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
                'email',
                'telephone',
                'statut',
                'rating',
                'rating_count',
            ],
            'length' => [
                2 => 100,
                150,
                20,
                20,
            ],
            'unique' => [
                3 => true,
            ],
            'nullable' => [
                4 => true,
                6 => true,
                true,
            ],
            'fetch' => [
                8 => 2,
            ],
            'sourceEntity' => [
                8 => 'App\\Entity\\Vendor',
            ],
            'mappedBy' => [
                8 => 'vendeur',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                8 => 'products',
            ],
            'targetEntity' => [
                8 => 'App\\Entity\\Product',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
