<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[ORM\Table(name: 'article')]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'id_article', type: Types::INTEGER)]
    private ?int $id_article = null;

    #[ORM\Column(name: 'titre', length: 255)]
    private ?string $titre = null;

    #[ORM\Column(name: 'contenu', type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(name: 'image_principale', length: 255, nullable: true)]
    private ?string $image_principale = null;

    #[ORM\Column(name: 'categorie', length: 100, nullable: true)]
    private ?string $categorie = null;

    #[ORM\Column(name: 'statut', length: 20, nullable: true)]
    private ?string $statut = null;

    #[ORM\Column(name: 'nombre_vues', type: Types::INTEGER)]
    private int $nombre_vues = 0;

    // ── IA fields ─────────────────────────────────────────────────
    /** Comma-separated keywords generated by AI e.g. "coaching,leadership,objectifs" */
    #[ORM\Column(name: 'mots_cles', length: 500, nullable: true)]
    private ?string $mots_cles = null;

    /** 2-sentence SEO summary generated by AI */
    #[ORM\Column(name: 'resume_ia', type: Types::TEXT, nullable: true)]
    private ?string $resume_ia = null;

    /** Tone detected by AI: Informatif | Motivant | Technique | Narratif */
    #[ORM\Column(name: 'ton_ia', length: 30, nullable: true)]
    private ?string $ton_ia = null;

    /** Category suggested by AI (may differ from current category) */
    #[ORM\Column(name: 'categorie_ia', length: 100, nullable: true)]
    private ?string $categorie_ia = null;

    // ── Trending field ────────────────────────────────────────────
    /** Float score computed by TrendingService. Higher = trending now */
    #[ORM\Column(name: 'trending_score', type: Types::FLOAT, nullable: true)]
    private ?float $trending_score = null;

    /** Timestamp of when trending_score was last computed */
    #[ORM\Column(name: 'trending_updated_at', type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $trending_updated_at = null;

    // ── Getters & Setters ─────────────────────────────────────────

    public function getIdArticle(): ?int { return $this->id_article; }

    public function getTitre(): ?string { return $this->titre; }
    public function setTitre(string $titre): static { $this->titre = $titre; return $this; }

    public function getContenu(): ?string { return $this->contenu; }
    public function setContenu(string $contenu): static { $this->contenu = $contenu; return $this; }

    public function getImagePrincipale(): ?string { return $this->image_principale; }
    public function setImagePrincipale(?string $v): static { $this->image_principale = $v; return $this; }

    public function getCategorie(): ?string { return $this->categorie; }
    public function setCategorie(?string $v): static { $this->categorie = $v; return $this; }

    public function getStatut(): ?string { return $this->statut; }
    public function setStatut(?string $v): static { $this->statut = $v; return $this; }

    public function getNombreVues(): int { return $this->nombre_vues; }
    public function setNombreVues(int $v): static { $this->nombre_vues = $v; return $this; }

    // IA
    public function getMotsCles(): ?string { return $this->mots_cles; }
    public function setMotsCles(?string $v): static { $this->mots_cles = $v; return $this; }

    /** Returns keywords as an array for easy use in Twig */
    public function getMotsClesArray(): array
    {
        if (!$this->mots_cles) return [];
        return array_filter(array_map('trim', explode(',', $this->mots_cles)));
    }

    public function getResumeIa(): ?string { return $this->resume_ia; }
    public function setResumeIa(?string $v): static { $this->resume_ia = $v; return $this; }

    public function getTonIa(): ?string { return $this->ton_ia; }
    public function setTonIa(?string $v): static { $this->ton_ia = $v; return $this; }

    public function getCategorieIa(): ?string { return $this->categorie_ia; }
    public function setCategorieIa(?string $v): static { $this->categorie_ia = $v; return $this; }

    // Trending
    public function getTrendingScore(): ?float { return $this->trending_score; }
    public function setTrendingScore(?float $v): static { $this->trending_score = $v; return $this; }

    public function getTrendingUpdatedAt(): ?\DateTimeImmutable { return $this->trending_updated_at; }
    public function setTrendingUpdatedAt(?\DateTimeImmutable $v): static { $this->trending_updated_at = $v; return $this; }

    /** Helper — is this article currently trending? */
    public function isTrending(): bool
    {
        return $this->trending_score !== null && $this->trending_score >= 10.0;
    }

    /** Helper — estimated reading time in minutes based on word count (avg 200 words/min) */
    public function getReadingTimeMinutes(): int
    {
        if (!$this->contenu) return 1;
        $words = str_word_count(strip_tags($this->contenu));
        return max(1, (int) ceil($words / 200));
    }
}
