<?php

namespace ContainerXkC7s72;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UJ3SrbPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uJ3SrbP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uJ3SrbP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationRepo' => ['privates', 'App\\Repository\\InscriptionEvenementRepository', 'getInscriptionEvenementRepositoryService', true],
        ], [
            'reservationRepo' => 'App\\Repository\\InscriptionEvenementRepository',
        ]);
    }
}
