<?php

namespace ContainerXkC7s72;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWaitlistServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\WaitlistService' shared autowired service.
     *
     * @return \App\Service\WaitlistService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'WaitlistService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\WaitlistService'])) {
            return $container->privates['App\\Service\\WaitlistService'];
        }

        $instance = new \App\Service\WaitlistService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), $a);

        if (isset($container->privates['App\\Service\\WaitlistService'])) {
            return $container->privates['App\\Service\\WaitlistService'];
        }

        return $container->privates['App\\Service\\WaitlistService'] = $instance;
    }
}
