<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Yry6ua\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Yry6ua/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container2Yry6ua.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container2Yry6ua\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container2Yry6ua\App_KernelProdContainer([
    'container.build_hash' => '2Yry6ua',
    'container.build_id' => 'a3e18a7b',
    'container.build_time' => 1777979626,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Yry6ua');
