<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vendor extends \App\Entity\Vendor implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'products' => [parent::class, 'products', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        "\0".parent::class."\0".'ratingCount' => [parent::class, 'ratingCount', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'products' => [parent::class, 'products', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
        'ratingCount' => [parent::class, 'ratingCount', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
