<?php

namespace ContainerK0zqQIb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MqYF9WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mq_YF9W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'repo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'waitlistService' => ['privates', 'App\\Service\\WaitlistService', 'getWaitlistServiceService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\EvenementRepository',
            'waitlistService' => 'App\\Service\\WaitlistService',
        ]);

        if (isset($container->privates['.service_locator.Mq_YF9W'])) {
            return $container->privates['.service_locator.Mq_YF9W'];
        }

        return $container->privates['.service_locator.Mq_YF9W'] = $instance;
    }
}
