<?php

namespace ContainerK0zqQIb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vrj3pfZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vrj3pfZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mailerService' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
            'qrCodeService' => ['privates', 'App\\Service\\QrCodeService', 'getQrCodeServiceService', true],
            'repo' => ['privates', 'App\\Repository\\InscriptionEvenementRepository', 'getInscriptionEvenementRepositoryService', true],
        ], [
            'em' => '?',
            'mailerService' => 'App\\Service\\MailerService',
            'notificationService' => 'App\\Service\\NotificationService',
            'qrCodeService' => 'App\\Service\\QrCodeService',
            'repo' => 'App\\Repository\\InscriptionEvenementRepository',
        ]);

        if (isset($container->privates['.service_locator.vrj3pfZ'])) {
            return $container->privates['.service_locator.vrj3pfZ'];
        }

        return $container->privates['.service_locator.vrj3pfZ'] = $instance;
    }
}
