<?php

namespace ContainerK0zqQIb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomaineCoachingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IevKdaG.App\Entity\DomaineCoaching' shared service.
     *
     * @return \App\Entity\DomaineCoaching
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IevKdaG": it needs an instance of "App\\Entity\\DomaineCoaching" but this type has been excluded in "config/services.yaml".');
    }
}
