<?php

namespace ContainerC667cQk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AhfkAy_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AhfkAy.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AhfkAy.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'repo' => ['privates', 'App\\Repository\\CoachRepository', 'getCoachRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\CoachRepository',
        ]);
    }
}
