<?php

namespace ContainerC667cQk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KgdbDKIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KgdbDKI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KgdbDKI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'httpClient' => ['privates', 'http_client.uri_template', 'getHttpClient_UriTemplateService', true],
            'productRepo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'promoService' => ['privates', 'App\\Service\\FlashPromotionService', 'getFlashPromotionServiceService', true],
        ], [
            'httpClient' => '?',
            'productRepo' => 'App\\Repository\\ProductRepository',
            'promoService' => 'App\\Service\\FlashPromotionService',
        ]);
    }
}
