<?php

namespace ContainerC667cQk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yg0NnMzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yg0NnMz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yg0NnMz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'reservation' => ['privates', '.errored..service_locator.Yg0NnMz.App\\Entity\\InscriptionEvenement', NULL, 'Cannot autowire service ".service_locator.Yg0NnMz": it needs an instance of "App\\Entity\\InscriptionEvenement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'reservation' => 'App\\Entity\\InscriptionEvenement',
        ]);
    }
}
