<?php

namespace ContainerC667cQk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BkXYWcsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bkXYWcs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bkXYWcs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
        ], [
            'productRepo' => 'App\\Repository\\ProductRepository',
            'requestStack' => '?',
        ]);
    }
}
