<?php

namespace ContainerC667cQk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ReservationController' shared autowired service.
     *
     * @return \App\Controller\ReservationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ReservationController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ReservationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'NotificationService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));
        $b = ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService'));
        $c = ($container->privates['App\\Repository\\DisponibiliteRepository'] ?? $container->load('getDisponibiliteRepositoryService'));
        $d = ($container->privates['App\\Repository\\CoachRepository'] ?? $container->load('getCoachRepositoryService'));
        $e = ($container->privates['App\\Repository\\NotificationRepository'] ?? $container->load('getNotificationRepositoryService'));
        $f = new \App\Service\NotificationService($a, $e);
        $g = ($container->privates['logger'] ?? self::getLoggerService($container));

        $container->services['App\\Controller\\ReservationController'] = $instance = new \App\Controller\ReservationController($a, $b, $c, $d, $e, new \App\Service\ReservationService($a, $b, $c, $d, $f, ($container->privates['App\\Service\\TelegramNotificationService'] ?? $container->load('getTelegramNotificationServiceService')), $g), $f, $g);

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ReservationController', $container));

        return $instance;
    }
}
