<?php

namespace ContainerC667cQk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestSmsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestSmsCommand' shared autowired service.
     *
     * @return \App\Command\TestSmsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'TestSmsCommand.php';

        $container->privates['App\\Command\\TestSmsCommand'] = $instance = new \App\Command\TestSmsCommand(($container->privates['App\\Service\\TelegramNotificationService'] ?? $container->load('getTelegramNotificationServiceService')));

        $instance->setName('app:test-sms');
        $instance->setDescription('Test sending an SMS');

        return $instance;
    }
}
