<?php

namespace Container4TbHyht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInscriptionEvenement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oQXGYC2.App\Entity\InscriptionEvenement' shared service.
     *
     * @return \App\Entity\InscriptionEvenement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oQXGYC2": it needs an instance of "App\\Entity\\InscriptionEvenement" but this type has been excluded in "config/services.yaml".');
    }
}
