<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHfrx1zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iHfrx1z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iHfrx1z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'promoService' => ['privates', 'App\\Service\\FlashPromotionService', 'getFlashPromotionServiceService', true],
        ], [
            'promoService' => 'App\\Service\\FlashPromotionService',
        ]);
    }
}
