<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A2fyDuEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A2fyDuE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A2fyDuE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vendorRepo' => ['privates', 'App\\Repository\\VendorRepository', 'getVendorRepositoryService', true],
        ], [
            'vendorRepo' => 'App\\Repository\\VendorRepository',
        ]);
    }
}
