<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ANHMGXzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ANHMGXz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ANHMGXz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'reviewService' => ['privates', 'App\\Service\\SocialReviewService', 'getSocialReviewServiceService', true],
        ], [
            'productRepo' => 'App\\Repository\\ProductRepository',
            'reviewService' => 'App\\Service\\SocialReviewService',
        ]);
    }
}
