<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomaineSuggestionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\DomaineSuggestionService' shared autowired service.
     *
     * @return \App\Service\DomaineSuggestionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DomaineSuggestionService.php';

        return $container->privates['App\\Service\\DomaineSuggestionService'] = new \App\Service\DomaineSuggestionService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['App\\Repository\\DomaineCoachingRepository'] ?? $container->load('getDomaineCoachingRepositoryService')), ($container->privates['logger'] ?? self::getLoggerService($container)), $container->getEnv('SERPAPI_KEY_DOMAINES'), $container->getEnv('GEMINI_API_KEY'), $container->getEnv('GEMINI_MODEL'));
    }
}
