<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashPromotionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FlashPromotionService' shared autowired service.
     *
     * @return \App\Service\FlashPromotionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FlashPromotionService.php';

        return $container->privates['App\\Service\\FlashPromotionService'] = new \App\Service\FlashPromotionService(\dirname(__DIR__, 4));
    }
}
