<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationMailServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RegistrationMailService' shared autowired service.
     *
     * @return \App\Service\RegistrationMailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RegistrationMailService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\RegistrationMailService'])) {
            return $container->privates['App\\Service\\RegistrationMailService'];
        }

        $instance = new \App\Service\RegistrationMailService($a, $container->getEnv('APP_URL'));

        if (isset($container->privates['App\\Service\\RegistrationMailService'])) {
            return $container->privates['App\\Service\\RegistrationMailService'];
        }

        return $container->privates['App\\Service\\RegistrationMailService'] = $instance;
    }
}
