<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecaptchaVerifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RecaptchaVerifier' shared autowired service.
     *
     * @return \App\Service\RecaptchaVerifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RecaptchaVerifier.php';

        return $container->privates['App\\Service\\RecaptchaVerifier'] = new \App\Service\RecaptchaVerifier(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('RECAPTCHA_SECRET'), $container->getEnv('bool:RECAPTCHA_ENABLED'));
    }
}
