<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramNotificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TelegramNotificationService' shared autowired service.
     *
     * @return \App\Service\TelegramNotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TelegramNotificationService.php';

        return $container->privates['App\\Service\\TelegramNotificationService'] = new \App\Service\TelegramNotificationService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)), $container->getEnv('TELEGRAM_BOT_TOKEN'), $container->getEnv('TELEGRAM_CHAT_ID'));
    }
}
