<?php

namespace ContainerMrWsUs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrendingServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TrendingService' shared autowired service.
     *
     * @return \App\Service\TrendingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TrendingService.php';

        return $container->privates['App\\Service\\TrendingService'] = new \App\Service\TrendingService(($container->privates['App\\Repository\\ArticleRepository'] ?? $container->load('getArticleRepositoryService')), ($container->privates['App\\Repository\\ArticleReactionRepository'] ?? $container->load('getArticleReactionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
