<?php

namespace ContainerE8ftRY8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UA1lN8SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UA1lN8S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailService' => ['privates', 'App\\Service\\RegistrationMailService', 'getRegistrationMailServiceService', true],
            'recaptchaVerifier' => ['privates', 'App\\Service\\RecaptchaVerifier', 'getRecaptchaVerifierService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'mailService' => 'App\\Service\\RegistrationMailService',
            'recaptchaVerifier' => 'App\\Service\\RecaptchaVerifier',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.UA1lN8S'])) {
            return $container->privates['.service_locator.UA1lN8S'];
        }

        return $container->privates['.service_locator.UA1lN8S'] = $instance;
    }
}
