<?php

namespace ContainerE8ftRY8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NWL8b6EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nWL8b6E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nWL8b6E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ai' => ['privates', 'App\\Service\\AIAnalyzerService', 'getAIAnalyzerServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'event' => ['privates', '.errored..service_locator.nWL8b6E.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.nWL8b6E": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ai' => 'App\\Service\\AIAnalyzerService',
            'em' => '?',
            'event' => 'App\\Entity\\Evenement',
        ]);
    }
}
