<?php

namespace ContainerE8ftRY8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XkEMxggService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XkEMxgg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'waitlist' => ['privates', 'App\\Service\\WaitlistService', 'getWaitlistServiceService', true],
        ], [
            'repo' => 'App\\Repository\\EvenementRepository',
            'waitlist' => 'App\\Service\\WaitlistService',
        ]);

        if (isset($container->privates['.service_locator.XkEMxgg'])) {
            return $container->privates['.service_locator.XkEMxgg'];
        }

        return $container->privates['.service_locator.XkEMxgg'] = $instance;
    }
}
