<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJk1uV89\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJk1uV89/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJk1uV89.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJk1uV89\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJk1uV89\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jk1uV89',
    'container.build_id' => 'f80d79ec',
    'container.build_time' => 1776200128,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJk1uV89');
