<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIwHpxZx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwHpxZx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIwHpxZx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIwHpxZx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIwHpxZx\App_KernelDevDebugContainer([
    'container.build_hash' => 'IwHpxZx',
    'container.build_id' => '88e8c626',
    'container.build_time' => 1775753102,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIwHpxZx');
