<?php

namespace ContainerLEJm8eG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B5Iixs8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B5Iixs8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B5Iixs8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'evenement' => ['privates', '.errored..service_locator.B5Iixs8.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.B5Iixs8": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'evenement' => 'App\\Entity\\Evenement',
            'slugger' => '?',
        ]);
    }
}
