<?php

namespace ContainerLEJm8eG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OQXGYC2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oQXGYC2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oQXGYC2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.oQXGYC2.App\\Entity\\InscriptionEvenement', NULL, 'Cannot autowire service ".service_locator.oQXGYC2": it needs an instance of "App\\Entity\\InscriptionEvenement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservation' => 'App\\Entity\\InscriptionEvenement',
        ]);
    }
}
