<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5q36EE9Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5q36EE9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5q36EE9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'vendorRepo' => ['privates', 'App\\Repository\\VendorRepository', 'getVendorRepositoryService', true],
        ], [
            'em' => '?',
            'slugger' => '?',
            'vendorRepo' => 'App\\Repository\\VendorRepository',
        ]);
    }
}
