<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R80toSService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.r80to_s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r80to_s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coach' => ['privates', '.errored..service_locator.r80to_s.App\\Entity\\Coach', NULL, 'Cannot autowire service ".service_locator.r80to_s": it needs an instance of "App\\Entity\\Coach" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'repo' => ['privates', 'App\\Repository\\CoachRepository', 'getCoachRepositoryService', true],
        ], [
            'coach' => 'App\\Entity\\Coach',
            'em' => '?',
            'repo' => 'App\\Repository\\CoachRepository',
        ]);
    }
}
