<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0iHwKYtService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.0iHwKYt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0iHwKYt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reviewService' => ['privates', 'App\\Service\\SocialReviewService', 'getSocialReviewServiceService', true],
        ], [
            'reviewService' => 'App\\Service\\SocialReviewService',
        ]);
    }
}
