<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyzeCommentairesCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\AnalyzeCommentairesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\AnalyzeCommentairesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:ai:analyze-commentaires', [], 'Run the local AI commentaire analysis model for one event or all events.', false, #[\Closure(name: 'App\\Command\\AnalyzeCommentairesCommand')] fn (): \App\Command\AnalyzeCommentairesCommand => ($container->privates['App\\Command\\AnalyzeCommentairesCommand'] ?? $container->load('getAnalyzeCommentairesCommandService')));
    }
}
