<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCoachStatisticsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\AdminCoachStatisticsController' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminCoachStatisticsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\AdminCoachStatisticsController'] = $instance = new \App\Controller\Admin\AdminCoachStatisticsController(new \App\Service\CoachStatisticsService(($container->privates['App\\Repository\\CoachRepository'] ?? $container->load('getCoachRepositoryService')), ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\RatingRepository'] ?? $container->load('getRatingRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Admin\\AdminCoachStatisticsController', $container));

        return $instance;
    }
}
