<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleReactionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ArticleReactionRepository' shared autowired service.
     *
     * @return \App\Repository\ArticleReactionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ArticleReactionRepository'] = new \App\Repository\ArticleReactionRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
