<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCoachControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\AdminCoachController' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminCoachController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\AdminCoachController'] = $instance = new \App\Controller\Admin\AdminCoachController(new \App\Service\CsvExportService(($container->privates['App\\Repository\\CoachRepository'] ?? $container->load('getCoachRepositoryService'))), new \App\Service\PhoneCountryDetectionService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService'))));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Admin\\AdminCoachController', $container));

        return $instance;
    }
}
