<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAIAnalyzerServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\AIAnalyzerService' shared autowired service.
     *
     * @return \App\Service\AIAnalyzerService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\AIAnalyzerService'] = new \App\Service\AIAnalyzerService(new \App\Model\CommentaireAnalysisModel(\dirname(__DIR__, 4)));
    }
}
