<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProductDashboardControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminProductDashboardController' shared autowired service.
     *
     * @return \App\Controller\AdminProductDashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminProductDashboardController'] = $instance = new \App\Controller\AdminProductDashboardController(($container->privates['App\\Service\\ProductService'] ?? $container->load('getProductServiceService')), ($container->privates['App\\Repository\\VendorRepository'] ?? $container->load('getVendorRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AdminProductDashboardController', $container));

        return $instance;
    }
}
