<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyzeCommentairesCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\AnalyzeCommentairesCommand' shared autowired service.
     *
     * @return \App\Command\AnalyzeCommentairesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\AnalyzeCommentairesCommand'] = $instance = new \App\Command\AnalyzeCommentairesCommand(($container->privates['App\\Repository\\EvenementRepository'] ?? $container->load('getEvenementRepositoryService')), ($container->privates['App\\Service\\AIAnalyzerService'] ?? $container->load('getAIAnalyzerServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:ai:analyze-commentaires');
        $instance->setDescription('Run the local AI commentaire analysis model for one event or all events.');

        return $instance;
    }
}
