<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireEvenementRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CommentaireEvenementRepository' shared autowired service.
     *
     * @return \App\Repository\CommentaireEvenementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CommentaireEvenementRepository'] = new \App\Repository\CommentaireEvenementRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
