<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoach3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.r80to_s.App\Entity\Coach' shared service.
     *
     * @return \App\Entity\Coach
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.r80to_s": it needs an instance of "App\\Entity\\Coach" but this type has been excluded in "config/services.yaml".');
    }
}
