<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoachTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CoachType' shared autowired service.
     *
     * @return \App\Form\CoachType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CoachType'] = new \App\Form\CoachType(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')));
    }
}
