<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoachControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CoachController' shared autowired service.
     *
     * @return \App\Controller\CoachController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Repository\\CoachRepository'] ?? $container->load('getCoachRepositoryService'));

        $container->services['App\\Controller\\CoachController'] = $instance = new \App\Controller\CoachController(new \App\Service\CoachService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), $a), $a, ($container->privates['App\\Repository\\RatingRepository'] ?? $container->load('getRatingRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CoachController', $container));

        return $instance;
    }
}
