<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatbotControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ChatbotController' shared autowired service.
     *
     * @return \App\Controller\ChatbotController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ChatbotController'] = $instance = new \App\Controller\ChatbotController(new \App\Service\ChatbotService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['App\\Repository\\CoachRepository'] ?? $container->load('getCoachRepositoryService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $container->getEnv('AI_API_URL'), $container->getEnv('AI_API_KEY'), $container->getEnv('AI_MODEL')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ChatbotController', $container));

        return $instance;
    }
}
