<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomaineSuggestionServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\DomaineSuggestionService' shared autowired service.
     *
     * @return \App\Service\DomaineSuggestionService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\DomaineSuggestionService'] = new \App\Service\DomaineSuggestionService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['App\\Repository\\DomaineCoachingRepository'] ?? $container->load('getDomaineCoachingRepositoryService')), ($container->privates['logger'] ?? self::getLoggerService($container)), $container->getEnv('SERPAPI_KEY_DOMAINES'), $container->getEnv('GEMINI_API_KEY'), $container->getEnv('GEMINI_MODEL'));
    }
}
