<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomaineCoachingTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\DomaineCoachingType' shared autowired service.
     *
     * @return \App\Form\DomaineCoachingType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\DomaineCoachingType'] = new \App\Form\DomaineCoachingType();
    }
}
