<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DefaultConfigurationService extends App_KernelProdContainer
{
    /*
     * Gets the private 'doctrine.orm.default_configuration' shared service.
     *
     * @return \Doctrine\ORM\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.orm.default_configuration'] = $instance = new \Doctrine\ORM\Configuration();

        $a = new \Doctrine\Persistence\Mapping\Driver\MappingDriverChain();
        $a->addDriver(new \Doctrine\ORM\Mapping\Driver\AttributeDriver([(\dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity')], true), 'App\\Entity');

        $instance->setEntityNamespaces(['App' => 'App\\Entity']);
        $instance->setMetadataCache(new \Symfony\Component\Cache\Adapter\PhpArrayAdapter(($container->targetDir.''.'/doctrine/orm/default_metadata.php'), new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
        $instance->setQueryCache(($container->privates['doctrine.system_cache_pool'] ?? $container->load('getDoctrine_SystemCachePoolService')));
        $instance->setResultCache(($container->privates['doctrine.result_cache_pool'] ?? $container->load('getDoctrine_ResultCachePoolService')));
        $instance->setMetadataDriverImpl(new \Doctrine\Bundle\DoctrineBundle\Mapping\MappingDriver($a, new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine.ulid_generator' => ['privates', 'doctrine.ulid_generator', 'getDoctrine_UlidGeneratorService', true],
            'doctrine.uuid_generator' => ['privates', 'doctrine.uuid_generator', 'getDoctrine_UuidGeneratorService', true],
        ], [
            'doctrine.ulid_generator' => '?',
            'doctrine.uuid_generator' => '?',
        ])));
        $instance->setProxyDir(($container->targetDir.''.'/doctrine/orm/Proxies'));
        $instance->setProxyNamespace('Proxies');
        $instance->setAutoGenerateProxyClasses(false);
        $instance->setSchemaIgnoreClasses([]);
        $instance->setClassMetadataFactoryName('Doctrine\\Bundle\\DoctrineBundle\\Mapping\\ClassMetadataFactory');
        $instance->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
        $instance->setNamingStrategy(new \Doctrine\ORM\Mapping\UnderscoreNamingStrategy(0, true));
        $instance->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
        $instance->setTypedFieldMapper(new \Doctrine\ORM\Mapping\DefaultTypedFieldMapper());
        $instance->setEntityListenerResolver(new \Doctrine\Bundle\DoctrineBundle\Mapping\ContainerEntityListenerResolver($container));
        $instance->setLazyGhostObjectEnabled(true);
        $instance->setIdentityGenerationPreferences([]);
        $instance->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Repository\\ArticleReactionRepository' => ['privates', 'App\\Repository\\ArticleReactionRepository', 'getArticleReactionRepositoryService', true],
            'App\\Repository\\ArticleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'App\\Repository\\CoachRepository' => ['privates', 'App\\Repository\\CoachRepository', 'getCoachRepositoryService', true],
            'App\\Repository\\CommandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'App\\Repository\\CommentaireEvenementRepository' => ['privates', 'App\\Repository\\CommentaireEvenementRepository', 'getCommentaireEvenementRepositoryService', true],
            'App\\Repository\\DisponibiliteRepository' => ['privates', 'App\\Repository\\DisponibiliteRepository', 'getDisponibiliteRepositoryService', true],
            'App\\Repository\\DomaineCoachingRepository' => ['privates', 'App\\Repository\\DomaineCoachingRepository', 'getDomaineCoachingRepositoryService', true],
            'App\\Repository\\EvenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'App\\Repository\\InscriptionEvenementRepository' => ['privates', 'App\\Repository\\InscriptionEvenementRepository', 'getInscriptionEvenementRepositoryService', true],
            'App\\Repository\\ProductRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'App\\Repository\\RatingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
            'App\\Repository\\ReservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'App\\Repository\\ReviewCacheRepository' => ['privates', 'App\\Repository\\ReviewCacheRepository', 'getReviewCacheRepositoryService', true],
            'App\\Repository\\RoleRepository' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
            'App\\Repository\\SignalementArticleRepository' => ['privates', 'App\\Repository\\SignalementArticleRepository', 'getSignalementArticleRepositoryService', true],
            'App\\Repository\\UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'App\\Repository\\VendorRepository' => ['privates', 'App\\Repository\\VendorRepository', 'getVendorRepositoryService', true],
        ], [
            'App\\Repository\\ArticleReactionRepository' => '?',
            'App\\Repository\\ArticleRepository' => '?',
            'App\\Repository\\CoachRepository' => '?',
            'App\\Repository\\CommandeRepository' => '?',
            'App\\Repository\\CommentaireEvenementRepository' => '?',
            'App\\Repository\\DisponibiliteRepository' => '?',
            'App\\Repository\\DomaineCoachingRepository' => '?',
            'App\\Repository\\EvenementRepository' => '?',
            'App\\Repository\\InscriptionEvenementRepository' => '?',
            'App\\Repository\\ProductRepository' => '?',
            'App\\Repository\\RatingRepository' => '?',
            'App\\Repository\\ReservationRepository' => '?',
            'App\\Repository\\ReviewCacheRepository' => '?',
            'App\\Repository\\RoleRepository' => '?',
            'App\\Repository\\SignalementArticleRepository' => '?',
            'App\\Repository\\UserRepository' => '?',
            'App\\Repository\\VendorRepository' => '?',
        ])));

        return $instance;
    }
}
