<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementFrontControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EvenementFrontController' shared autowired service.
     *
     * @return \App\Controller\EvenementFrontController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EvenementFrontController'] = $instance = new \App\Controller\EvenementFrontController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\EvenementFrontController', $container));

        return $instance;
    }
}
