<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontendBlogControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FrontendBlogController' shared autowired service.
     *
     * @return \App\Controller\FrontendBlogController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FrontendBlogController'] = $instance = new \App\Controller\FrontendBlogController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\FrontendBlogController', $container));

        return $instance;
    }
}
