<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeminiChatServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\GeminiChatService' shared autowired service.
     *
     * @return \App\Service\GeminiChatService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\GeminiChatService'] = new \App\Service\GeminiChatService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GEMINI_API_KEY'), $container->getEnv('GEMINI_MODEL'));
    }
}
