<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarketplaceControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MarketplaceController' shared autowired service.
     *
     * @return \App\Controller\MarketplaceController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MarketplaceController'] = $instance = new \App\Controller\MarketplaceController(($container->privates['App\\Service\\ProductService'] ?? $container->load('getProductServiceService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Service\\TelegramNotificationService'] ?? $container->load('getTelegramNotificationServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\MarketplaceController', $container));

        return $instance;
    }
}
