<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ProductService' shared autowired service.
     *
     * @return \App\Service\ProductService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ProductService'] = new \App\Service\ProductService(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')));
    }
}
