<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrCodeServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\QrCodeService' shared autowired service.
     *
     * @return \App\Service\QrCodeService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\QrCodeService'] = new \App\Service\QrCodeService();
    }
}
