<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ReservationController' shared autowired service.
     *
     * @return \App\Controller\ReservationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));
        $b = ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService'));
        $c = ($container->privates['App\\Repository\\DisponibiliteRepository'] ?? $container->load('getDisponibiliteRepositoryService'));
        $d = ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService'));
        $e = ($container->privates['logger'] ?? self::getLoggerService($container));

        $container->services['App\\Controller\\ReservationController'] = $instance = new \App\Controller\ReservationController($a, $b, $c, new \App\Service\ReservationService($a, $b, $c, ($container->privates['App\\Repository\\CoachRepository'] ?? $container->load('getCoachRepositoryService')), $d, new \App\Service\TwilioSmsService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $e, $container->getEnv('TWILIO_ACCOUNT_SID'), $container->getEnv('TWILIO_AUTH_TOKEN'), $container->getEnv('TWILIO_FROM_NUMBER'), $container->getEnv('TWILIO_TO_NUMBER')), $e), $d, $e);

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ReservationController', $container));

        return $instance;
    }
}
