<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecaptchaVerifierService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\RecaptchaVerifier' shared autowired service.
     *
     * @return \App\Service\RecaptchaVerifier
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\RecaptchaVerifier'] = new \App\Service\RecaptchaVerifier(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('RECAPTCHA_SECRET'), $container->getEnv('bool:RECAPTCHA_ENABLED'));
    }
}
