<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationMailServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\RegistrationMailService' shared autowired service.
     *
     * @return \App\Service\RegistrationMailService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\RegistrationMailService'] = new \App\Service\RegistrationMailService(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), $container->getEnv('APP_URL'));
    }
}
