<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\RatingController' shared autowired service.
     *
     * @return \App\Controller\RatingController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RatingController'] = $instance = new \App\Controller\RatingController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\RatingRepository'] ?? $container->load('getRatingRepositoryService')), ($container->privates['logger'] ?? self::getLoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\RatingController', $container));

        return $instance;
    }
}
