<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedAdminCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\SeedAdminCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\SeedAdminCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:seed-admin', [], 'Seeds an admin user into the database', false, #[\Closure(name: 'App\\Command\\SeedAdminCommand')] fn (): \App\Command\SeedAdminCommand => ($container->privates['App\\Command\\SeedAdminCommand'] ?? $container->load('getSeedAdminCommandService')));
    }
}
