<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeWebhookControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\StripeWebhookController' shared autowired service.
     *
     * @return \App\Controller\StripeWebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\StripeWebhookController'] = $instance = new \App\Controller\StripeWebhookController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\StripeWebhookController', $container));

        return $instance;
    }
}
