<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedUserCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\SeedUserCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\SeedUserCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:seed-user', [], 'Seeds a regular user into the database', false, #[\Closure(name: 'App\\Command\\SeedUserCommand')] fn (): \App\Command\SeedUserCommand => ($container->privates['App\\Command\\SeedUserCommand'] ?? $container->load('getSeedUserCommandService')));
    }
}
