<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialReviewServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\SocialReviewService' shared autowired service.
     *
     * @return \App\Service\SocialReviewService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\SocialReviewService'] = new \App\Service\SocialReviewService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
