<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedAdminCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\SeedAdminCommand' shared autowired service.
     *
     * @return \App\Command\SeedAdminCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\SeedAdminCommand'] = $instance = new \App\Command\SeedAdminCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:seed-admin');
        $instance->setDescription('Seeds an admin user into the database');

        return $instance;
    }
}
