<?php

namespace Container2Yry6ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWaitlistServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\WaitlistService' shared autowired service.
     *
     * @return \App\Service\WaitlistService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\WaitlistService'])) {
            return $container->privates['App\\Service\\WaitlistService'];
        }

        $instance = new \App\Service\WaitlistService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), $a);

        if (isset($container->privates['App\\Service\\WaitlistService'])) {
            return $container->privates['App\\Service\\WaitlistService'];
        }

        return $container->privates['App\\Service\\WaitlistService'] = $instance;
    }
}
