<?php

namespace ContainerNmiVgK1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ObEkA1QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ObEkA1Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ObEkA1Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coach' => ['privates', '.errored..service_locator.ObEkA1Q.App\\Entity\\Coach', NULL, 'Cannot autowire service ".service_locator.ObEkA1Q": it needs an instance of "App\\Entity\\Coach" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'coach' => 'App\\Entity\\Coach',
            'em' => '?',
        ]);
    }
}
