<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SignalementArticle extends \App\Entity\SignalementArticle implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date_signalement' => [parent::class, 'date_signalement', null, 16],
        "\0".parent::class."\0".'date_traitement' => [parent::class, 'date_traitement', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id_article' => [parent::class, 'id_article', null, 16],
        "\0".parent::class."\0".'id_signalement' => [parent::class, 'id_signalement', null, 16],
        "\0".parent::class."\0".'id_user' => [parent::class, 'id_user', null, 16],
        "\0".parent::class."\0".'motif' => [parent::class, 'motif', null, 16],
        "\0".parent::class."\0".'remarque_admin' => [parent::class, 'remarque_admin', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        'date_signalement' => [parent::class, 'date_signalement', null, 16],
        'date_traitement' => [parent::class, 'date_traitement', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id_article' => [parent::class, 'id_article', null, 16],
        'id_signalement' => [parent::class, 'id_signalement', null, 16],
        'id_user' => [parent::class, 'id_user', null, 16],
        'motif' => [parent::class, 'motif', null, 16],
        'remarque_admin' => [parent::class, 'remarque_admin', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
