<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InscriptionEvenement extends \App\Entity\InscriptionEvenement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateReservation' => [parent::class, 'dateReservation', null, 16],
        "\0".parent::class."\0".'devise' => [parent::class, 'devise', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'evenement' => [parent::class, 'evenement', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'montantTotal' => [parent::class, 'montantTotal', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'nombrePlaces' => [parent::class, 'nombrePlaces', null, 16],
        "\0".parent::class."\0".'paidAt' => [parent::class, 'paidAt', null, 16],
        "\0".parent::class."\0".'paymentStatus' => [parent::class, 'paymentStatus', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'stripeSessionId' => [parent::class, 'stripeSessionId', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'dateReservation' => [parent::class, 'dateReservation', null, 16],
        'devise' => [parent::class, 'devise', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'evenement' => [parent::class, 'evenement', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'montantTotal' => [parent::class, 'montantTotal', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'nombrePlaces' => [parent::class, 'nombrePlaces', null, 16],
        'paidAt' => [parent::class, 'paidAt', null, 16],
        'paymentStatus' => [parent::class, 'paymentStatus', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'stripeSessionId' => [parent::class, 'stripeSessionId', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
