<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CommentaireEvenement extends \App\Entity\CommentaireEvenement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'contenu' => [parent::class, 'contenu', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'evenement' => [parent::class, 'evenement', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null, 16],
        'contenu' => [parent::class, 'contenu', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'evenement' => [parent::class, 'evenement', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'note' => [parent::class, 'note', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
