<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rating extends \App\Entity\Rating implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coach' => [parent::class, 'coach', null, 16],
        "\0".parent::class."\0".'commentaire' => [parent::class, 'commentaire', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'dateModification' => [parent::class, 'dateModification', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'coach' => [parent::class, 'coach', null, 16],
        'commentaire' => [parent::class, 'commentaire', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'dateModification' => [parent::class, 'dateModification', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'note' => [parent::class, 'note', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
