<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \App\Entity\Commande implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateCommande' => [parent::class, 'dateCommande', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'modePaiement' => [parent::class, 'modePaiement', null, 16],
        "\0".parent::class."\0".'montantTotal' => [parent::class, 'montantTotal', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        'dateCommande' => [parent::class, 'dateCommande', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'modePaiement' => [parent::class, 'modePaiement', null, 16],
        'montantTotal' => [parent::class, 'montantTotal', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
