<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'idProduit' => [parent::class, 'idProduit', null, 16],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null, 16],
        "\0".parent::class."\0".'nomProduit' => [parent::class, 'nomProduit', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        "\0".parent::class."\0".'ratingCount' => [parent::class, 'ratingCount', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'stockDisponible' => [parent::class, 'stockDisponible', null, 16],
        "\0".parent::class."\0".'vendeur' => [parent::class, 'vendeur', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'idProduit' => [parent::class, 'idProduit', null, 16],
        'imageUrl' => [parent::class, 'imageUrl', null, 16],
        'nomProduit' => [parent::class, 'nomProduit', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
        'ratingCount' => [parent::class, 'ratingCount', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'stockDisponible' => [parent::class, 'stockDisponible', null, 16],
        'vendeur' => [parent::class, 'vendeur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
