<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticleReaction extends \App\Entity\ArticleReaction implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null, 16],
        "\0".parent::class."\0".'date_reaction' => [parent::class, 'date_reaction', null, 16],
        "\0".parent::class."\0".'id_article' => [parent::class, 'id_article', null, 16],
        "\0".parent::class."\0".'id_reaction' => [parent::class, 'id_reaction', null, 16],
        "\0".parent::class."\0".'id_user' => [parent::class, 'id_user', null, 16],
        "\0".parent::class."\0".'is_anonymous' => [parent::class, 'is_anonymous', null, 16],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null, 16],
        "\0".parent::class."\0".'type_reaction' => [parent::class, 'type_reaction', null, 16],
        'avis' => [parent::class, 'avis', null, 16],
        'date_reaction' => [parent::class, 'date_reaction', null, 16],
        'id_article' => [parent::class, 'id_article', null, 16],
        'id_reaction' => [parent::class, 'id_reaction', null, 16],
        'id_user' => [parent::class, 'id_user', null, 16],
        'is_anonymous' => [parent::class, 'is_anonymous', null, 16],
        'note' => [parent::class, 'note', null, 16],
        'type_reaction' => [parent::class, 'type_reaction', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
