<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Coach extends \App\Entity\Coach implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'biographie' => [parent::class, 'biographie', null, 16],
        "\0".parent::class."\0".'disponibilite' => [parent::class, 'disponibilite', null, 16],
        "\0".parent::class."\0".'domaine' => [parent::class, 'domaine', null, 16],
        "\0".parent::class."\0".'domaineCoaching' => [parent::class, 'domaineCoaching', null, 16],
        "\0".parent::class."\0".'experienceAnnees' => [parent::class, 'experienceAnnees', null, 16],
        "\0".parent::class."\0".'idCoach' => [parent::class, 'idCoach', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'noteMoyenne' => [parent::class, 'noteMoyenne', null, 16],
        "\0".parent::class."\0".'numTel' => [parent::class, 'numTel', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'tarifHoraire' => [parent::class, 'tarifHoraire', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'biographie' => [parent::class, 'biographie', null, 16],
        'disponibilite' => [parent::class, 'disponibilite', null, 16],
        'domaine' => [parent::class, 'domaine', null, 16],
        'domaineCoaching' => [parent::class, 'domaineCoaching', null, 16],
        'experienceAnnees' => [parent::class, 'experienceAnnees', null, 16],
        'idCoach' => [parent::class, 'idCoach', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'noteMoyenne' => [parent::class, 'noteMoyenne', null, 16],
        'numTel' => [parent::class, 'numTel', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'tarifHoraire' => [parent::class, 'tarifHoraire', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
