<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \App\Entity\Article implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'categorie_ia' => [parent::class, 'categorie_ia', null, 16],
        "\0".parent::class."\0".'contenu' => [parent::class, 'contenu', null, 16],
        "\0".parent::class."\0".'id_article' => [parent::class, 'id_article', null, 16],
        "\0".parent::class."\0".'image_principale' => [parent::class, 'image_principale', null, 16],
        "\0".parent::class."\0".'mots_cles' => [parent::class, 'mots_cles', null, 16],
        "\0".parent::class."\0".'nombre_vues' => [parent::class, 'nombre_vues', null, 16],
        "\0".parent::class."\0".'resume_ia' => [parent::class, 'resume_ia', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        "\0".parent::class."\0".'ton_ia' => [parent::class, 'ton_ia', null, 16],
        "\0".parent::class."\0".'trending_score' => [parent::class, 'trending_score', null, 16],
        "\0".parent::class."\0".'trending_updated_at' => [parent::class, 'trending_updated_at', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'categorie_ia' => [parent::class, 'categorie_ia', null, 16],
        'contenu' => [parent::class, 'contenu', null, 16],
        'id_article' => [parent::class, 'id_article', null, 16],
        'image_principale' => [parent::class, 'image_principale', null, 16],
        'mots_cles' => [parent::class, 'mots_cles', null, 16],
        'nombre_vues' => [parent::class, 'nombre_vues', null, 16],
        'resume_ia' => [parent::class, 'resume_ia', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
        'ton_ia' => [parent::class, 'ton_ia', null, 16],
        'trending_score' => [parent::class, 'trending_score', null, 16],
        'trending_updated_at' => [parent::class, 'trending_updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
